version: "3"
services:
  server:
    container_name: server
    image: server
    build:
      context: .
      dockerfile: server/Dockerfile.server
    expose:
      - 1488
    ports:
     - "1488:1488"
    volumes:
      - ./gen-go/commuticator:/go/src/github.com/Dimitriy14/communicators/thrift/gen-go/commuticator


  client:
    container_name: client
    image: client
    build:
      context: .
      dockerfile: client/Dockerfile.client
    depends_on:
      - server
    volumes:
      - ./gen-go/commuticator:/go/src/github.com/Dimitriy14/communicators/thrift/gen-go/commuticator
